[package]
name = "musit-core"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
flate2.workspace = true
regex.workspace = true
once_cell.workspace = true
chrono.workspace = true
dirs.workspace = true
notify.workspace = true

[dev-dependencies]
tempfile.workspace = true
